create table Sensor
(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name      varchar(100) UNIQUE NOT NULL
);

create table Measurement
(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sensor varchar REFERENCES Sensor (name) ON DELETE CASCADE,
    value          float     NOT NULL,
    raining        boolean NOT NULL,
    created_at timestamp
)